# Generated by Django 3.2.23 on 2023-11-23 12:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='placeholder_k3nekm', max_length=255, verbose_name='image'),
        ),
    ]
