# Generated by Django 3.2.23 on 2023-11-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(choices=[('Physical', 'Physical'), ('Emotional', 'Emotional'), ('Psychological', 'Psychological')], default='Physical', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
