# Generated by Django 3.2.23 on 2023-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_pseudonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='health_concerns',
            field=models.CharField(blank=True, choices=[('Prostate Cancer', 'Prostate Cancer'), ('Erectile Dysfunction', 'Erectile Dysfunction'), ('Testicular Cancer', 'Testicular Cancer'), ('Low Testosterone', 'Low Testosterone'), ('Benign Prostatic Hyperplasia (BPH)', 'Benign Prostatic Hyperplasia (BPH)'), ('Cardiovascular Health', 'Cardiovascular Health'), ('Type 2 Diabetes', 'Type 2 Diabetes'), ('Obesity', 'Obesity'), ('Hair Loss', 'Hair Loss'), ('Infertility', 'Infertility'), ('Chronic Pain', 'Chronic Pain'), ('Sleep Apnea', 'Sleep Apnea'), ('Depression', 'Depression'), ('Anxiety', 'Anxiety'), ('Stress', 'Stress'), ('Anger Management', 'Anger Management'), ('Grief and Loss', 'Grief and Loss'), ('Relationship Issues', 'Relationship Issues'), ('Body Image Concerns', 'Body Image Concerns'), ('Substance Abuse', 'Substance Abuse'), ('Work-Life Balance', 'Work-Life Balance'), ('Self-Esteem', 'Self-Esteem'), ('Suicide Prevention', 'Suicide Prevention'), ('Post-Traumatic Stress Disorder (PTSD)', 'Post-Traumatic Stress Disorder (PTSD)'), ('Attention Deficit Hyperactivity Disorder (ADHD)', 'ADHD'), ('Bipolar Disorder', 'Bipolar Disorder'), ('Schizophrenia', 'Schizophrenia'), ('Obsessive-Compulsive Disorder (OCD)', 'OCD'), ('Personality Disorders', 'Personality Disorders'), ('Social Anxiety Disorder', 'Social Anxiety Disorder'), ('Eating Disorders', 'Eating Disorders'), ('Phobias', 'Phobias'), ('Panic Disorder', 'Panic Disorder'), ('Addiction Recovery', 'Addiction Recovery'), ('Emotional Regulation', 'Emotional Regulation'), ('Coping with Trauma', 'Coping with Trauma'), ('Mental Health Stigma', 'Mental Health Stigma'), ('Workplace Stress', 'Workplace Stress'), ('Loneliness', 'Loneliness'), ('Midlife Crisis', 'Midlife Crisis'), ('Empty Nest Syndrome', 'Empty Nest Syndrome'), ('Parenting Stress', 'Parenting Stress'), ('Financial Stress', 'Financial Stress'), ('Retirement Planning', 'Retirement Planning'), ('Aging and Health', 'Aging and Health'), ('Memory Concerns', 'Memory Concerns'), ('Sexual Health and Aging', 'Sexual Health and Aging'), ('Cognitive Decline', 'Cognitive Decline'), ('Joint Health', 'Joint Health')], max_length=255, null=True),
        ),
    ]
