# Generated by Django 3.2.23 on 2023-11-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_health_concerns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='health_concerns',
        ),
        migrations.AddField(
            model_name='profile',
            name='health_concerns',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Tag'),
        ),
    ]
