# Generated by Django 3.2.23 on 2023-11-24 16:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20231124_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='health_concerns',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/ksjl86/image/upload/v1700840217/z9ashu5ydegcow5lsgtz.png', max_length=255, verbose_name='image'),
        ),
    ]
