# Generated by Django 3.2.23 on 2023-11-24 16:55

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20231124_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='health_concerns',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Tag'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
