# Generated by Django 3.2.23 on 2023-11-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20231124_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='health_concerns',
            field=models.ManyToManyField(blank=True, null=True, to='profiles.Tag'),
        ),
    ]
